# Generated by Django 5.2 on 2025-05-31 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
