# Generated by Django 5.2 on 2025-06-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libro_fecha_publicacion_libro_paginas_libro_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('avatars', models.ImageField(blank=True, null=True, upload_to='media/avatars/')),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='media/portadas/'),
        ),
    ]
